### PR TITLE
Delete CNAME

### PR DESCRIPTION
**Pull request by getsetbro**
rm the CNAME so we can have a little peek at it -> paulirish.github.io/w3fools

### CODE REVIEW

**Comment by paulirish** [comment]
Yeah i let the domain expire 3 days ago..

**Comment by ljharb** [comment]
Are you planning on renewing it? It doesn't look available to register, but it's certainly also not loading content.

**Comment by paulirish** [comment]
fuck it ill add 3 more years for the domain. it gets like 150 users a day.

it's back online now. https://www.w3fools.com

**Comment by ljharb** [comment]
If you ever get tired of adding more, I will always be happy to steward it, no matter how few users it's getting :-)

**Pull request closed without merging**
